version: '3'
services:
    reverse:
        image: nginx:1.15-alpine
        restart: unless-stopped
        volumes:
            - ./data/cert:/usr/local/share/ca-certificates
        network_mode: "host"
    janus:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./janus
        volumes:
            - /mnt/videology/recordings:/recordings
        network_mode: "host"
    client:
        volumes:
            - /app/node_modules
        network_mode: "host"
    rabbit:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./rabbit
        network_mode: "host"