version: '3'
services:
    reverse:
        image: nginx:1.15-alpine
        restart: unless-stopped
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/cert:/usr/local/share/ca-certificates
            - ./client:/var/www
        ports:
            - "80:80"
            - "443:443"
            - "8089:8089"
            - "8189:443"
        depends_on: 
            - janus
        
    janus:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: ./janus
        volumes:
            - ~/videology/recordings:/recordings            